### ISSUE TITLE
Action execution failed

### ISSUE THREAD

**Issue by virtualjj** [alestic/aws-lambda-codepipeline-site-generator-hugo#5]
I'm still having trouble getting this to work. 

I'm now getting the following error message in CodePipeline after making a commit to CodeCommit:

![image](https://cloud.githubusercontent.com/assets/10323889/21982187/85b96a18-dc2e-11e6-879e-1f7e8047b914.png)

I have confirmed that the IAM role does indeed have the correct permissions:

![image](https://cloud.githubusercontent.com/assets/10323889/21982242/bd3cc584-dc2e-11e6-9bc6-e0bb3c40a66b.png)

I used the following settings when launching the CloudFormation template:

![image](https://cloud.githubusercontent.com/assets/10323889/21982260/dc7b0410-dc2e-11e6-8eb2-f9bdd3fe2fde.png)

![image](https://cloud.githubusercontent.com/assets/10323889/21982266/e2a71392-dc2e-11e6-8d5b-1edd176a0530.png)

I have confirmed that I can get a test site running with this theme locally:

![image](https://cloud.githubusercontent.com/assets/10323889/21982281/f2f29050-dc2e-11e6-84f6-6530aebb8912.png)

Here are the actual commands that I used to setup the Hugo site:

![image](https://cloud.githubusercontent.com/assets/10323889/21982292/068e5928-dc2f-11e6-94bd-c63d9e17bfbe.png)

Probably shouldn't have put the .gitignore file here:

![image](https://cloud.githubusercontent.com/assets/10323889/21982425/9999abe6-dc2f-11e6-9674-c4d5fd308f5f.png)

![image](https://cloud.githubusercontent.com/assets/10323889/21982547/2c350efa-dc30-11e6-970f-24566b828103.png)

![image](https://cloud.githubusercontent.com/assets/10323889/21982381/636386a0-dc2f-11e6-82a0-c298bf42ba2a.png)

Okay, so I will remove the .gitignore for the themes and try again:

![image](https://cloud.githubusercontent.com/assets/10323889/21982564/429e8626-dc30-11e6-9220-f3bbf1a00b08.png)

Okay, pushed without issue:

![image](https://cloud.githubusercontent.com/assets/10323889/21982588/63bb901a-dc30-11e6-8339-cddfcf5748f8.png)

Unfortunately, same error:

![image](https://cloud.githubusercontent.com/assets/10323889/21983234/913f5690-dc33-11e6-9739-5cc4566da8e5.png)

Here are the CloudWatch messages:

```
START RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4 Version: $LATEST
['./hugo', '--source=/tmp/tmpYD1dAp', '--destination=/tmp/tmpRB1YPG', '--theme', 'beautifulhugo']
ERROR return code: 255
ERROR output: Error: Unable to find theme Directory: /tmp/tmpYD1dAp/themes/beautifulhugo


ERROR:CalledProcessError()
Traceback (most recent call last):
File "/var/task/index.py", line 78, in handler
generate_static_site(source_dir, site_dir, user_parameters)
File "/var/task/index.py", line 105, in generate_static_site
print(subprocess.check_output(command, stderr=subprocess.STDOUT))
File "/usr/lib64/python2.7/subprocess.py", line 574, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['./hugo', '--source=/tmp/tmpYD1dAp', '--destination=/tmp/tmpRB1YPG', '--theme', 'beautifulhugo']' returned non-zero exit status 255
Parameter validation failed:
Invalid type for parameter failureDetails.message, value: Command '['./hugo', '--source=/tmp/tmpYD1dAp', '--destination=/tmp/tmpRB1YPG', '--theme', 'beautifulhugo']' returned non-zero exit status 255, type: <class 'subprocess.CalledProcessError'>, valid types: <type 'basestring'>: ParamValidationError
Traceback (most recent call last):
File "/var/task/index.py", line 90, in handler
code_pipeline.put_job_failure_result(jobId=job_id, failureDetails={'message': e, 'type': 'JobFailed'})
File "/var/runtime/botocore/client.py", line 251, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 513, in _make_api_call
api_params, operation_model, context=request_context)
File "/var/runtime/botocore/client.py", line 566, in _convert_to_request_dict
api_params, operation_model)
File "/var/runtime/botocore/validate.py", line 270, in serialize_to_request
raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter failureDetails.message, value: Command '['./hugo', '--source=/tmp/tmpYD1dAp', '--destination=/tmp/tmpRB1YPG', '--theme', 'beautifulhugo']' returned non-zero exit status 255, type: <class 'subprocess.CalledProcessError'>, valid types: <type 'basestring'>

END RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4
REPORT RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4	Duration: 371.55 ms	Billed Duration: 400 ms Memory Size: 1536 MB	Max Memory Used: 46 MB	
START RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4 Version: $LATEST
['./hugo', '--source=/tmp/tmpb8wyCc', '--destination=/tmp/tmpPpnPyp', '--theme', 'beautifulhugo']
ERROR return code: 255
ERROR output: Error: Unable to find theme Directory: /tmp/tmpb8wyCc/themes/beautifulhugo


ERROR:CalledProcessError()
Traceback (most recent call last):
File "/var/task/index.py", line 78, in handler
generate_static_site(source_dir, site_dir, user_parameters)
File "/var/task/index.py", line 105, in generate_static_site
print(subprocess.check_output(command, stderr=subprocess.STDOUT))
File "/usr/lib64/python2.7/subprocess.py", line 574, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['./hugo', '--source=/tmp/tmpb8wyCc', '--destination=/tmp/tmpPpnPyp', '--theme', 'beautifulhugo']' returned non-zero exit status 255
Parameter validation failed:
Invalid type for parameter failureDetails.message, value: Command '['./hugo', '--source=/tmp/tmpb8wyCc', '--destination=/tmp/tmpPpnPyp', '--theme', 'beautifulhugo']' returned non-zero exit status 255, type: <class 'subprocess.CalledProcessError'>, valid types: <type 'basestring'>: ParamValidationError
Traceback (most recent call last):
File "/var/task/index.py", line 90, in handler
code_pipeline.put_job_failure_result(jobId=job_id, failureDetails={'message': e, 'type': 'JobFailed'})
File "/var/runtime/botocore/client.py", line 251, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 513, in _make_api_call
api_params, operation_model, context=request_context)
File "/var/runtime/botocore/client.py", line 566, in _convert_to_request_dict
api_params, operation_model)
File "/var/runtime/botocore/validate.py", line 270, in serialize_to_request
raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter failureDetails.message, value: Command '['./hugo', '--source=/tmp/tmpb8wyCc', '--destination=/tmp/tmpPpnPyp', '--theme', 'beautifulhugo']' returned non-zero exit status 255, type: <class 'subprocess.CalledProcessError'>, valid types: <type 'basestring'>

END RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4
REPORT RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4	Duration: 302.40 ms	Billed Duration: 400 ms Memory Size: 1536 MB	Max Memory Used: 52 MB	
START RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4 Version: $LATEST
['./hugo', '--source=/tmp/tmpDSSZUy', '--destination=/tmp/tmpG8K0Ov', '--theme', 'beautifulhugo']
ERROR return code: 255
ERROR output: Error: Unable to find theme Directory: /tmp/tmpDSSZUy/themes/beautifulhugo


ERROR:CalledProcessError()
Traceback (most recent call last):
File "/var/task/index.py", line 78, in handler
generate_static_site(source_dir, site_dir, user_parameters)
File "/var/task/index.py", line 105, in generate_static_site
print(subprocess.check_output(command, stderr=subprocess.STDOUT))
File "/usr/lib64/python2.7/subprocess.py", line 574, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['./hugo', '--source=/tmp/tmpDSSZUy', '--destination=/tmp/tmpG8K0Ov', '--theme', 'beautifulhugo']' returned non-zero exit status 255
Parameter validation failed:
Invalid type for parameter failureDetails.message, value: Command '['./hugo', '--source=/tmp/tmpDSSZUy', '--destination=/tmp/tmpG8K0Ov', '--theme', 'beautifulhugo']' returned non-zero exit status 255, type: <class 'subprocess.CalledProcessError'>, valid types: <type 'basestring'>: ParamValidationError
Traceback (most recent call last):
File "/var/task/index.py", line 90, in handler
code_pipeline.put_job_failure_result(jobId=job_id, failureDetails={'message': e, 'type': 'JobFailed'})
File "/var/runtime/botocore/client.py", line 251, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 513, in _make_api_call
api_params, operation_model, context=request_context)
File "/var/runtime/botocore/client.py", line 566, in _convert_to_request_dict
api_params, operation_model)
File "/var/runtime/botocore/validate.py", line 270, in serialize_to_request
raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter failureDetails.message, value: Command '['./hugo', '--source=/tmp/tmpDSSZUy', '--destination=/tmp/tmpG8K0Ov', '--theme', 'beautifulhugo']' returned non-zero exit status 255, type: <class 'subprocess.CalledProcessError'>, valid types: <type 'basestring'>

END RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4
REPORT RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4	Duration: 218.03 ms	Billed Duration: 300 ms Memory Size: 1536 MB	Max Memory Used: 54 MB	
START RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4 Version: $LATEST
['./hugo', '--source=/tmp/tmpae6BLB', '--destination=/tmp/tmpfq8UGE', '--theme', 'beautifulhugo']
ERROR return code: 255
ERROR output: Error: Unable to find theme Directory: /tmp/tmpae6BLB/themes/beautifulhugo


ERROR:CalledProcessError()
Traceback (most recent call last):
File "/var/task/index.py", line 78, in handler
generate_static_site(source_dir, site_dir, user_parameters)
File "/var/task/index.py", line 105, in generate_static_site
print(subprocess.check_output(command, stderr=subprocess.STDOUT))
File "/usr/lib64/python2.7/subprocess.py", line 574, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['./hugo', '--source=/tmp/tmpae6BLB', '--destination=/tmp/tmpfq8UGE', '--theme', 'beautifulhugo']' returned non-zero exit status 255
Parameter validation failed:
Invalid type for parameter failureDetails.message, value: Command '['./hugo', '--source=/tmp/tmpae6BLB', '--destination=/tmp/tmpfq8UGE', '--theme', 'beautifulhugo']' returned non-zero exit status 255, type: <class 'subprocess.CalledProcessError'>, valid types: <type 'basestring'>: ParamValidationError
Traceback (most recent call last):
File "/var/task/index.py", line 90, in handler
code_pipeline.put_job_failure_result(jobId=job_id, failureDetails={'message': e, 'type': 'JobFailed'})
File "/var/runtime/botocore/client.py", line 251, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 513, in _make_api_call
api_params, operation_model, context=request_context)
File "/var/runtime/botocore/client.py", line 566, in _convert_to_request_dict
api_params, operation_model)
File "/var/runtime/botocore/validate.py", line 270, in serialize_to_request
raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter failureDetails.message, value: Command '['./hugo', '--source=/tmp/tmpae6BLB', '--destination=/tmp/tmpfq8UGE', '--theme', 'beautifulhugo']' returned non-zero exit status 255, type: <class 'subprocess.CalledProcessError'>, valid types: <type 'basestring'>

END RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4
REPORT RequestId: 79283dd4-dbe6-11e6-97c0-77b591bf95e4	Duration: 227.61 ms	Billed Duration: 300 ms Memory Size: 1536 MB	Max Memory Used: 58 MB
```	

If I manually sync the local repo to S3 directly the test Hugo site comes up:

![image](https://cloud.githubusercontent.com/assets/10323889/21983842/78aa7a30-dc36-11e6-9a8b-89cd6f8d21df.png)

**Comment by ehammond** [comment]
@virtualjj This is the important error being reported by Hugo:

ERROR output: Error: Unable to find theme Directory: /tmp/tmpb8wyCc/themes/beautifulhugo

You need to add and commit those theme files into the same git repo as the rest of the site source content.

This may involve removing the themes/beautifulhugo/.git directory before you can add them to the containing Git repo.

**Comment by virtualjj** [comment]
I thought I had done that but I didn't. Rebuilding and will give it another try - thanks for your patience!

**Comment by virtualjj** [comment]
Success! 
As expected, it was all me and my git ignorance. Thanks for your patience and hand holding!

![image](https://cloud.githubusercontent.com/assets/10323889/22049652/141f1ec0-dd78-11e6-926c-da9d55dff739.png)

**Comment by ehammond** [comment]
Thanks for reporting this originally. It helped uncover a defect that I corrected in the source.
